# Choosing an Image:
# https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html
version: "3.7"
services:
  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    volumes:
      - ${LOCAL_WORKING_DIR:-/root/notebook-files}:/home/jovyan/work
    ports:
      - "8888:8888"
    restart: unless-stopped
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    command: "start-notebook.sh --NotebookApp.password=${ACCESS_TOKEN}"
    labels:
      - traefik.http.routers.jupyter.rule=Host(`${JUPYTER_URL}`)
      - traefik.http.routers.jupyter.tls=true
      - traefik.http.routers.jupyter.tls.certresolver=lets-encrypt
      - traefik.port=8888
    networks:
      - web
    env_file:
      - .env

networks:
  web:
    external: true
