version: "3.8"

services:
  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    volumes:
      - ${LOCAL_WORKING_DIR:-/root/notebook-files}:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - 8888:8888
    restart: unless-stopped
    command: "start-notebook.sh --NotebookApp.password=${ACCESS_TOKEN}"
    labels:
      - traefik.http.routers.jupyter.rule=Host(`${JUPYTER_URL}`)
      - traefik.http.routers.jupyter.tls=true
      - traefik.http.routers.jupyter.tls.certresolver=lets-encrypt
      - traefik.port=8888
    networks:
      - web

networks:
  web:
    external: true
