version: "3.8"

services:
  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    volumes:
      - ${LOCAL_WORKING_DIR:-/root/notebook-files}:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - 8888:8888
    restart: unless-stopped
    command: "start-notebook.sh --NotebookApp.password=${ACCESS_TOKEN}"
