version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: ${UID}:${GID}
    volumes:
      - ./database.db:/database.db
      - ./filebrowser.json:/.filebrowser.json
      - ${MEDIA_DIR:-./media}:/srv
    ports:
      - 8081:80
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
