version: "3.8"

services:
  traefik:
    image: traefik
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/traefik.toml:/traefik.toml
      - ./data/traefik_dynamic.toml:/traefik_dynamic.toml
      - ./data/acme.json:/acme.json
    restart: unless-stopped

networks:
  web:
    external: true
