services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ${MEDIA_DIR:-./media}:/media:ro
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: 'unless-stopped'
    # environment:
      # - JELLYFIN_PublishedServerUrl=http://example.com
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
