version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    restart: unless-stopped
    labels:
      - traefik.http.routers.portainer.rule=Host(`${PORTAINER_URL}`)
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=lets-encrypt
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    networks:
      - web

volumes:
  portainer_data:

networks:
  web:
    external: true
