version: "3.7"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  postgres-data:
    
