version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /tmp/stacks:/tmp/stacks
    restart: unless-stopped
    environment:
      - DOCKGE_STACKS_DIR=/tmp/stacks
